### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by ketra21** [ray2019/CourseMaterial#2]
**错误信息描述**
错误信息内容：
![可截图说明](可截图说明)
https://github.com/ray2019/CourseMaterial/blob/master/Course/Course3_ExplorationDataAnalysis.md
错误信息位置：
       描述文件名称
![image](https://user-images.githubusercontent.com/38323732/50276562-3221a680-047d-11e9-93d8-6412cac3027f.png)

**其他信息说明**
添加其他信息

**Comment by ray2019** [comment]
thanks
